"""add created_at to atletas

Revision ID: 0c1aaa4950f4
Revises: 2b6f1f76ec23
Create Date: 2025-12-18 14:21:13.855639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1aaa4950f4'
down_revision: Union[str, Sequence[str], None] = '2b6f1f76ec23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atletas', 'created_at')
    # ### end Alembic commands ###
